spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 901877280290-eg4m6ak793fiit2pmmjviphgvg3d9hri.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email