spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:mysql://localhost:3306/board?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root1234
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

