spring:
  profiles:
    include:
      - oauth
  datasource:
    url: jdbc:mysql://localhost:3306/danguen?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
file:
  user:
    image:
      path: src/main/resources/userImage/
  article:
    image:
      path: src/main/resources/articleImage/



