spring:
  profiles:
    include:
      - oauth
      - local
      - websocket
      - h2
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true








